name: listenable_widget
description: "A widget that listens to a ChangeNotifier and rebuilds when it changes."
version: 0.1.0
homepage: "https://seg.veenstra.dev"
repository: "https://github.com/SEGVeenstra/flutter_listenable_widget"

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
